[package]
name = "simple-engine"
version = "0.0.1"
edition = "2021"

[dependencies]
vulkano = "0.34.1"
winit = "0.29.10"
bytemuck = "1.14.0"

[profile.dev]
opt-level = 1

[profile.release]
codegen-units = 1
lto = false

[build]
rustflags = ["-C", "target-cpu=native"]
